INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (1, 1, 'WRANGLER', 2023, 1, 1, 25, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (2, 2, 'BOLT EV', 2020, 2, 3, 238, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (3, 3, 'NIRO', 2019, 2, 3, 239, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (4, 4, 'LEAF', 2014, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (5, 5, 'MODEL X', 2020, 2, 3, 289, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (6, 5, 'MODEL Y', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (7, 5, 'MODEL S', 2013, 2, 3, 208, 69900.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (8, 3, 'SOUL', 2016, 2, 3, 93, 31950.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (9, 6, 'PRIUS PRIME', 2017, 1, 3, 39, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (10, 7, 'FUSION', 2016, 1, 1, 21, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (11, 5, 'MODEL 3', 2022, 2, 3, 220, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (12, 8, '330E', 2023, 1, 1, 14, 44100.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (13, 9, 'XC60', 2022, 1, 1, 17, 52900.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (14, 10, 'CORSAIR', 2023, 1, 1, 28, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (15, 8, 'X5', 2024, 1, 3, 40, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (16, 11, 'RZ', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (17, 12, 'CLARITY', 2020, 1, 3, 47, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (18, 13, 'PS2', 2021, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (19, 6, 'RAV4', 2013, 2, 3, 103, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (20, 6, 'RAV4 PRIME', 2024, 1, 3, 42, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (21, 14, 'E-TRON', 2019, 2, 3, 204, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (22, 9, 'XC90', 2023, 1, 1, 19, 64950.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (23, 15, 'KONA', 2020, 2, 3, 258, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (24, 7, 'F-150', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (25, 16, '500', 2017, 2, 3, 87, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (26, 17, 'I-PACE', 2019, 2, 3, 234, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (27, 18, 'PACIFICA', 2021, 1, 3, 32, 39995.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (28, 15, 'TUCSON', 2023, 1, 3, 33, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (29, 7, 'ESCAPE', 2022, 1, 3, 37, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (30, 3, 'SPORTAGE', 2025, 1, 3, 34, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (31, 2, 'VOLT', 2013, 1, 3, 53, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (32, 6, 'PRIUS PLUG-IN', 2015, 1, 1, 6, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (33, 7, 'FOCUS', 2016, 2, 3, 76, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (34, 1, 'GRAND CHEROKEE', 2023, 1, 1, 25, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (35, 7, 'C-MAX', 2014, 1, 1, 19, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (36, 8, 'I3', 2016, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (37, 8, 'I4', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (38, 19, 'E-GOLF', 2019, 2, 3, 125, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (39, 2, 'SPARK', 2014, 2, 3, 82, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (40, 20, 'HARDTOP', 2021, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (41, 21, 'C-CLASS', 2016, 1, 1, 11, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (42, 15, 'IONIQ', 2020, 1, 1, 29, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (43, 3, 'SOUL EV', 2017, 2, 3, 93, 32250.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (44, 3, 'EV6', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (45, 22, 'SOLTERRA', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (46, 23, 'CX-90', 2024, 1, 1, 26, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (47, 9, 'XC40', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (48, 8, 'X3', 2021, 1, 1, 17, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (49, 3, 'EV9', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (50, 24, 'R1T', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (51, 14, 'Q5 E', 2025, 1, 1, 18, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (52, 25, 'I-MIEV', 2012, 2, 3, 62, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (53, 8, '745E', 2021, 1, 1, 16, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (54, 3, 'SORENTO', 2024, 1, 3, 32, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (55, 25, 'OUTLANDER', 2021, 1, 3, 38, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (56, 11, 'RX', 2024, 1, 3, 37, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (57, 8, '530E', 2019, 1, 1, 16, 53400.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (58, 2, 'BOLT EUV', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (59, 8, 'IX', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (60, 15, 'KONA ELECTRIC', 2021, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (61, 15, 'IONIQ 5', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (62, 7, 'MUSTANG MACH-E', 2021, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (63, 24, 'R1S', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (64, 14, 'A3', 2017, 1, 1, 16, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (65, 14, 'Q4', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (66, 21, 'EQE-CLASS SEDAN', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (67, 5, 'CYBERTRUCK', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (68, 26, 'TAYCAN', 2021, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (69, 2, 'EQUINOX EV', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (70, 7, 'TRANSIT', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (71, 19, 'ID.4', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (72, 11, 'NX', 2022, 1, 3, 37, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (73, 10, 'AVIATOR', 2020, 1, 1, 21, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (74, 2, 'SILVERADO EV', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (75, 26, 'CAYENNE', 2017, 1, 1, 14, 81100.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (76, 2, 'BLAZER EV', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (77, 15, 'SONATA', 2017, 1, 1, 27, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (78, 4, 'ARIYA', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (79, 21, 'EQE-CLASS SUV', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (80, 8, 'I5', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (81, 12, 'PROLOGUE', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (82, 27, 'ZDX', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (83, 28, 'GV60', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (84, 6, 'BZ4X', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (85, 29, 'LYRIQ', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (86, 21, 'EQS-CLASS SEDAN', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (87, 16, '500E', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (88, 21, 'EQB-CLASS', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (89, 9, 'C40', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (90, 20, 'COUNTRYMAN', 2023, 1, 1, 12, 36900.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (91, 21, 'GLC-CLASS', 2019, 1, 1, 10, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (92, 30, 'TONALE', 2025, 1, 3, 33, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (93, 14, 'E-TRON GT', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (94, 21, 'EQS-CLASS SUV', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (95, 15, 'IONIQ 6', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (96, 22, 'CROSSTREK', 2019, 1, 1, 17, 34995.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (97, 9, 'V60', 2024, 1, 3, 41, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (98, 31, 'AIR', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (99, 15, 'SANTA FE', 2022, 1, 3, 30, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (100, 32, 'HUMMER EV PICKUP', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (101, 29, 'OPTIQ', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (102, 33, 'RANGE ROVER SPORT', 2023, 1, 1, 19, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (103, 9, 'S60', 2022, 1, 3, 41, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (104, 9, 'S90', 2018, 1, 1, 21, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (105, 14, 'Q6', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (106, 26, 'PANAMERA', 2019, 1, 1, 14, 184400.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (107, 14, 'E-TRON SPORTBACK', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (108, 14, 'Q5', 2022, 1, 1, 22, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (109, 32, 'HUMMER EV SUV', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (110, 19, 'ID. BUZZ', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (111, 14, 'SQ8', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (112, 29, 'ELR', 2016, 1, 3, 37, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (113, 34, 'FORTWO ELECTRIC DRIVE', 2013, 2, 3, 58, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (114, 35, 'HORNET', 2024, 1, 3, 32, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (115, 23, 'CX-70', 2025, 1, 1, 26, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (116, 14, 'Q8', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (117, 21, 'GLE-CLASS', 2017, 1, 3, 49, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (118, 5, 'ROADSTER', 2010, 2, 3, 245, 110950.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (119, 26, 'MACAN', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (120, 21, 'B-CLASS', 2015, 2, 3, 87, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (121, 34, 'FORTWO', 2017, 2, 3, 68, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (122, 8, 'I8', 2017, 1, 1, 14, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (123, 3, 'OPTIMA', 2018, 1, 1, 29, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (124, 36, 'OCEAN', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (125, 8, 'I7', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (126, 15, 'IONIQ 5 N', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (127, 14, 'RS E-TRON GT', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (128, 28, 'GV70', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (129, 33, 'RANGE ROVER', 2025, 1, 1, 19, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (130, 13, 'POLESTAR 3', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (131, 21, 'G-CLASS', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (132, 21, 'S-CLASS', 2024, 1, 1, 12, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (133, 34, 'EQ FORTWO', 2018, 2, 3, 58, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (134, 9, 'EX30', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (135, 37, 'VF 8', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (136, 11, 'TX', 2024, 1, 3, 33, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (137, 8, 'XM', 2024, 1, 3, 31, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (138, 9, 'EX90', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (139, 38, 'CITY', 2011, 2, 3, 100, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (140, 12, 'ACCORD', 2014, 1, 1, 13, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (141, 8, '550E', 2025, 1, 3, 40, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (142, 9, 'EX40', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (143, 23, 'MX-30', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (144, 35, 'CHARGER', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (145, 8, 'M5', 2025, 1, 1, 25, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (146, 8, '750E', 2024, 1, 3, 36, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (147, 39, 'ONE', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (148, 40, 'ZEVO', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (149, 7, 'RANGER', 2000, 2, 3, 58, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (150, 14, 'A7 E', 2021, 1, 1, 24, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (151, 8, '740E', 2018, 1, 1, 14, 90700.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (152, 32, 'SIERRA EV', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (153, 21, 'ESPRINTER', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (154, 36, 'KARMA', 2012, 1, 3, 33, 102000.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (155, 41, 'FLYING SPUR', 2022, 1, 3, 45, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (156, 8, '745LE', 2022, 1, 1, 16, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (157, 28, 'G80', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (158, 24, 'EDV', 2022, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (159, 42, 'SPECTRE', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (160, 43, 'REVUELTO', 2024, 1, 1, 6, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (161, 1, 'WAGONEER S', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (162, 29, 'CT6', 2018, 1, 3, 31, 75095.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (163, 44, 'WHEEGO', 2010, 1, 3, 100, 32995.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (164, 26, '918', 2015, 1, 1, 12, 845000.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (165, 2, 'BRIGHTDROP 400', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (166, 41, 'BENTAYGA', 2024, 1, 1, 23, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (167, 45, 'TRANSIT CONNECT ELECTRIC', 2011, 2, 3, 56, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (168, 14, 'SQ6', 2025, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (169, 21, 'AMG GT', 2025, 1, 3, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (170, 46, 'PROMASTER 3500', 2024, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (171, 6, 'MIRAI', 2023, 2, 2, 0, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (172, 14, 'A8 E', 2020, 1, 1, 17, 0.00);
INSERT INTO evs.models OVERRIDING SYSTEM VALUE (id, make_id, model_name, model_year, ev_type, cafv_type, electric_range, base_msrp) VALUES (173, 21, 'SL-CLASS', 2025, 1, 3, 0, 0.00);

SELECT pg_catalog.setval('evs.models_id_seq', 173, true);



