replicaCount: 1

image:
  repository: pdughi/carwebapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=carwebapi;Username=postgres;Password=Password"

resources: {}