replicaCount: 1

revisionHistoryLimit: 1

image:
  repository: pdughi/carwebapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=carwebapi;Username=postgres;Password=Password"

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: "200"
    memory: 64Mi